version: 2
jobs:
  build:
    working_directory: ~/vote-plan
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-vote-plan-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - run: node node_modules/protractor/bin/webdriver-manager update  # ensure all the required webdrivers are installed
      - save_cache:
          key: v1-vote-plan-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run test -- --no-watch --no-progress --browsers=FirefoxHeadlessCI
      - run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
